INFO     root:test_01_login.py:27 ==========开始执行用例：login_03==========
INFO     root:runcase.py:31 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 START-·-·-·-·-·-·-·-·-·-
INFO     root:handleyaml.py:94 Yaml测试用例基础架构检查通过
INFO     root:runcase.py:50 重组后的用例信息：{'name': '登录失败（错误用户名、正确密码）', 'description': '输入错误用户名，正确密码，登录失败', 'request': {'data': {'unityId': False, 'username': 'admin1', 'gossip': 'r0Z0KPg+LIDvL0LlD+hyGy0EnDh00zD6wvD0muaDhRqcen7t4gM8Uapp8cN12IM5EWr4NAaUFnQsd66iKxhl2CBS7n/7l685YADhFz937tH5wKnJiuAZoJhJEdh3dIaYU+tLHel1xYWnQ95x2jgimP3Zl/qcmZiruamLWCC9KlQ='}, 'method': 'post', 'address': '/api/auth/v1/auth/login', 'headers': {'Content-Type': 'application/json', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/systemAdminLog'}}, 'validate': {'code': 200, 'jsonpath': [{'path': '$.msg', 'value': '用户名或密码错误', 'type': '=='}]}, 'epic': '用户登录', 'feature': '用户登录模块', 'story': '用户登录接口', 'base_url': 'https://192.168.148.174:31000', 'caseid': 'login_03'}
INFO     root:runcase.py:81 请求地址：https://192.168.148.174:31000/api/auth/v1/auth/login
INFO     root:runcase.py:82 请求方法：post
INFO     root:runcase.py:83 请求头：{'Content-Type': 'application/json', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/systemAdminLog'}
INFO     root:runcase.py:93 请求参数：{'unityId': False, 'username': 'admin1', 'gossip': 'r0Z0KPg+LIDvL0LlD+hyGy0EnDh00zD6wvD0muaDhRqcen7t4gM8Uapp8cN12IM5EWr4NAaUFnQsd66iKxhl2CBS7n/7l685YADhFz937tH5wKnJiuAZoJhJEdh3dIaYU+tLHel1xYWnQ95x2jgimP3Zl/qcmZiruamLWCC9KlQ='}
INFO     root:runcase.py:155 请求接口结果： {'statusCode': 1048835, 'msg': '用户名或密码错误'}
INFO     root:checkresult.py:152 code断言通过, 期望状态码:200, 实际状态码:200
INFO     root:checkresult.py:109 json断言通过, 期望结果'{'path': '$.msg', 'value': '用户名或密码错误', 'type': '=='}', 实际结果'用户名或密码错误'
INFO     root:runcase.py:61 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 END-·-·-·-·-·-·-·-·-·-