INFO     root:test_02_usersync.py:56 ==========开始执行用例：usersync_config_test_01==========
INFO     root:runcase.py:29 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 START-·-·-·-·-·-·-·-·-·-
INFO     root:handleyaml.py:94 Yaml测试用例基础架构检查通过
INFO     root:runcase.py:45 重组后的用例信息：{'name': '测试LADP数据源配置成功', 'description': '填写正确的LDAP数据源配置，点击测试', 'request': {'data': {'type': 'domain', 'configs': '{"name":"自动化测试70.235数据源修改","host":"192.168.70.235","port":"389","username":"xiantest\\\\administrator","password":"Ws-123456abc","base":"DC=xiantest,DC=com","org":"ou=北京明朝万达","isEncrypt":false,"userFilter":"","groupFilter":"","isIncrement":false}'}, 'method': 'post', 'address': '/api/usersync/v1/config/test', 'headers': {'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6IjI3MTM3NmQzLTBiZDktNDQ0Ni05ZGU5LThlMDZmM2YwM2Q4ZCIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiIyNzEzNzZkMy0wYmQ5LTQ0NDYtOWRlOS04ZTA2ZjNmMDNkOGQiLCJleHAiOjE2ODcxOTM3MzMsImlhdCI6MTY4NzAxMzczM30.Biu_6v1RwD72vA1X9gTejk7wW0bRoGbthwJGX28Y0XqDcwnzZ5VxENlK6o8nogaP5oEhcuhUrITOGgpvz2gh6w', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/userSync'}}, 'validate': {'code': 200, 'response': {'statusCode': 0, 'msg': 'success'}}, 'epic': '用户管理', 'feature': '用户同步管理-用户同步', 'story': '测试数据源配置接口', 'base_url': 'https://192.168.148.174:31000', 'caseid': 'usersync_config_test_01'}
INFO     root:runcase.py:81 请求地址：https://192.168.148.174:31000/api/usersync/v1/config/test
INFO     root:runcase.py:82 请求方法：post
INFO     root:runcase.py:83 请求头：{'Content-Type': 'application/json', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhdWQiOiJhcHBsaWNhdGlvbiIsInN1YiI6IjI3MTM3NmQzLTBiZDktNDQ0Ni05ZGU5LThlMDZmM2YwM2Q4ZCIsImlzcyI6ImJtc19zZXJ2ZXIiLCJzZXNzaW9uSWQiOiIyNzEzNzZkMy0wYmQ5LTQ0NDYtOWRlOS04ZTA2ZjNmMDNkOGQiLCJleHAiOjE2ODcxOTM3MzMsImlhdCI6MTY4NzAxMzczM30.Biu_6v1RwD72vA1X9gTejk7wW0bRoGbthwJGX28Y0XqDcwnzZ5VxENlK6o8nogaP5oEhcuhUrITOGgpvz2gh6w', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/userSync'}
INFO     root:runcase.py:93 请求参数：{'type': 'domain', 'configs': '{"name":"自动化测试70.235数据源修改","host":"192.168.70.235","port":"389","username":"xiantest\\\\administrator","password":"Ws-123456abc","base":"DC=xiantest,DC=com","org":"ou=北京明朝万达","isEncrypt":false,"userFilter":"","groupFilter":"","isIncrement":false}'}
DEBUG    urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): 192.168.148.174:31000
DEBUG    urllib3.connectionpool:connectionpool.py:456 https://192.168.148.174:31000 "POST /api/usersync/v1/config/test HTTP/1.1" 200 32
INFO     root:runcase.py:147 请求接口结果： {'statusCode': 0, 'msg': 'success'}
INFO     root:checkresult.py:111 code断言通过, 期望状态码:200, 实际状态码:200
INFO     root:checkresult.py:46 返回结果断言通过, 期望返回值:{'statusCode': 0, 'msg': 'success'}, 实际返回值:{'statusCode': 0, 'msg': 'success'}
INFO     root:runcase.py:61 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 END-·-·-·-·-·-·-·-·-·-