[32mINFO    [0m root:test_01_login.py:27 ==========开始执行用例：login_03==========
[32mINFO    [0m root:runcase.py:31 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 START-·-·-·-·-·-·-·-·-·-
[32mINFO    [0m root:handleyaml.py:94 Yaml测试用例基础架构检查通过
[32mINFO    [0m root:runcase.py:50 重组后的用例信息：{'name': '登录失败（错误用户名、正确密码）', 'description': '输入错误用户名，正确密码，登录失败', 'request': {'data': {'unityId': False, 'username': 'admin1', 'gossip': 'QpFMCca7JWICdkqdTF7sBJ9zvbVnzwVLz/AXALcidQoZOXZ1E4ZZZtAJS5drBOW8h8K9bgn/1q2Wff+EzgIrx4raKg+1Znrt1lRMRnO8eu/cNrwtuh4QBcU0T2isISuYJ4reUvH0d8ypcQI5yBGSFQ4KwpIi9Te6H86pFD04oec='}, 'method': 'post', 'address': '/api/auth/v1/auth/login', 'headers': {'Content-Type': 'application/json', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/systemAdminLog'}}, 'validate': {'code': 200, 'jsonpath': [{'path': '$.msg', 'value': '用户名或密码错误', 'type': '=='}]}, 'epic': '用户登录', 'feature': '用户登录模块', 'story': '用户登录接口', 'base_url': 'https://192.168.148.174:31000', 'caseid': 'login_03'}
[32mINFO    [0m root:runcase.py:81 请求地址：https://192.168.148.174:31000/api/auth/v1/auth/login
[32mINFO    [0m root:runcase.py:82 请求方法：post
[32mINFO    [0m root:runcase.py:83 请求头：{'Content-Type': 'application/json', 'Referer': 'https://192.168.148.174:31000/sub-app-unity/systemAdminLog'}
[32mINFO    [0m root:runcase.py:93 请求参数：{'unityId': False, 'username': 'admin1', 'gossip': 'QpFMCca7JWICdkqdTF7sBJ9zvbVnzwVLz/AXALcidQoZOXZ1E4ZZZtAJS5drBOW8h8K9bgn/1q2Wff+EzgIrx4raKg+1Znrt1lRMRnO8eu/cNrwtuh4QBcU0T2isISuYJ4reUvH0d8ypcQI5yBGSFQ4KwpIi9Te6H86pFD04oec='}
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1003 Starting new HTTPS connection (1): 192.168.148.174:31000
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:456 https://192.168.148.174:31000 "POST /api/auth/v1/auth/login HTTP/1.1" 200 55
[32mINFO    [0m root:runcase.py:155 请求接口结果： {'statusCode': 1048835, 'msg': '用户名或密码错误'}
[32mINFO    [0m root:checkresult.py:152 code断言通过, 期望状态码:200, 实际状态码:200
[32mINFO    [0m root:checkresult.py:109 json断言通过, 期望结果'{'path': '$.msg', 'value': '用户名或密码错误', 'type': '=='}', 实际结果'用户名或密码错误'
[32mINFO    [0m root:runcase.py:61 -·-·-·-·-·-·-·-·-·-发送请求并接受信息 END-·-·-·-·-·-·-·-·-·-